export type Difficulty = 'cet4' | 'cet6' | 'ielts';

export type WordEntry = {
  word: string;
  meaning: string;
};

export const WORDS_DB: Record<Difficulty, WordEntry[]> = {
  cet4: [
    { word: 'abandon', meaning: 'v. 放弃，抛弃' },
    { word: 'ability', meaning: 'n. 能力，才干' },
    { word: 'abnormal', meaning: 'adj. 异常的，反常的' },
    { word: 'aboard', meaning: 'adv./prep. 在船、飞机、车上' },
    { word: 'abolish', meaning: 'v. 废除，取消' },
    { word: 'abrupt', meaning: 'adj. 突然的，唐突的' },
    { word: 'absence', meaning: 'n. 缺席，不在' },
    { word: 'absolute', meaning: 'adj. 绝对的，完全的' },
    { word: 'absorb', meaning: 'v. 吸收，吸引' },
    { word: 'abstract', meaning: 'adj. 抽象的 n. 摘要' },
    { word: 'abundant', meaning: 'adj. 丰富的，充裕的' },
    { word: 'abuse', meaning: 'v./n. 滥用，虐待' },
    { word: 'academic', meaning: 'adj. 学术的，学院的' },
    { word: 'accelerate', meaning: 'v. 加速，促进' },
    { word: 'accent', meaning: 'n. 口音，重音' },
    { word: 'acceptable', meaning: 'adj. 可接受的' },
    { word: 'acceptance', meaning: 'n. 接受，赞同' },
    { word: 'access', meaning: 'n. 进入，途径 v. 访问' },
    { word: 'accident', meaning: 'n. 事故，意外' },
    { word: 'accommodate', meaning: 'v. 容纳，提供住宿' },
    { word: 'accompany', meaning: 'v. 陪伴，伴随' },
    { word: 'accomplish', meaning: 'v. 完成，实现' },
    { word: 'account', meaning: 'n. 账户，账目 v. 解释' },
    { word: 'accurate', meaning: 'adj. 准确的，精确的' },
    { word: 'accuse', meaning: 'v. 指控，谴责' },
    { word: 'achieve', meaning: 'v. 实现，达到' },
    { word: 'acknowledge', meaning: 'v. 承认，确认' },
    { word: 'acquire', meaning: 'v. 获得，取得' },
    { word: 'adapt', meaning: 'v. 适应，改编' },
    { word: 'adequate', meaning: 'adj. 充足的，合适的' },
    { word: 'adjust', meaning: 'v. 调整，调节' },
    { word: 'administration', meaning: 'n. 管理，行政部门' },
    { word: 'admission', meaning: 'n. 承认，入场费' },
    { word: 'adopt', meaning: 'v. 采纳，收养' },
    { word: 'advance', meaning: 'v./n. 前进，进展' },
    { word: 'advantage', meaning: 'n. 优势，益处' },
    { word: 'advertise', meaning: 'v. 做广告，宣传' },
    { word: 'affect', meaning: 'v. 影响，感动' },
    { word: 'afford', meaning: 'v. 买得起，承担得起' },
    { word: 'agency', meaning: 'n. 代理机构' },
    { word: 'agenda', meaning: 'n. 议程，日程表' },
    { word: 'agriculture', meaning: 'n. 农业' },
    { word: 'aid', meaning: 'n./v. 帮助，援助' },
    { word: 'aim', meaning: 'n. 目标 v. 旨在' },
    { word: 'alcohol', meaning: 'n. 酒精' },
    { word: 'allocate', meaning: 'v. 分配，拨出' },
    { word: 'allowance', meaning: 'n. 津贴，零用钱' },
    { word: 'alternative', meaning: 'n./adj. 替代选择，可替代的' },
    { word: 'amaze', meaning: 'v. 使惊奇' },
    { word: 'ambition', meaning: 'n. 野心，抱负' },
    { word: 'analysis', meaning: 'n. 分析' },
    { word: 'ancestor', meaning: 'n. 祖先，祖宗' },
    { word: 'announce', meaning: 'v. 宣布，通告' },
    { word: 'annual', meaning: 'adj. 每年的，年度的' },
    { word: 'anxiety', meaning: 'n. 焦虑，担心' },
    { word: 'apparent', meaning: 'adj. 明显的，显然的' },
    { word: 'appeal', meaning: 'v./n. 呼吁，吸引力' },
    { word: 'application', meaning: 'n. 申请，应用' },
    { word: 'appoint', meaning: 'v. 任命，约定' },
    { word: 'appreciate', meaning: 'v. 感激，欣赏' },
    { word: 'approach', meaning: 'v./n. 接近，方法' },
    { word: 'approve', meaning: 'v. 批准，赞成' },
    { word: 'argue', meaning: 'v. 争论，主张' },
    { word: 'arrange', meaning: 'v. 安排，整理' },
    { word: 'aspect', meaning: 'n. 方面，角度' },
    { word: 'assess', meaning: 'v. 评估，评价' },
    { word: 'assign', meaning: 'v. 分配，布置' },
    { word: 'assist', meaning: 'v. 帮助，协助' },
    { word: 'assume', meaning: 'v. 假定，承担' },
    { word: 'atmosphere', meaning: 'n. 气氛，大气层' },
    { word: 'attach', meaning: 'v. 附上，依恋' },
    { word: 'attempt', meaning: 'v./n. 尝试' },
    { word: 'attend', meaning: 'v. 参加，照顾' },
    { word: 'attitude', meaning: 'n. 态度，看法' },
    { word: 'attract', meaning: 'v. 吸引' },
    { word: 'average', meaning: 'adj./n. 平均的，平均数' },
    { word: 'avoid', meaning: 'v. 避免' },
    { word: 'award', meaning: 'n./v. 奖项，授予' },
    { word: 'awful', meaning: 'adj. 糟糕的，可怕的' },
    { word: 'backward', meaning: 'adj./adv. 向后的，落后的' },
    { word: 'bankrupt', meaning: 'adj. 破产的 v. 使破产' },
    { word: 'barely', meaning: 'adv. 几乎不，勉强' },
    { word: 'bargain', meaning: 'n. 廉价品 v. 讨价还价' },
    { word: 'barrier', meaning: 'n. 障碍，屏障' },
    { word: 'behalf', meaning: 'n. 代表，利益' },
    { word: 'behavior', meaning: 'n. 行为，举止' },
    { word: 'being', meaning: 'n. 存在，生物' },
    { word: 'belief', meaning: 'n. 信仰，相信' },
    { word: 'benefit', meaning: 'n. 利益 v. 有益于' },
    { word: 'blame', meaning: 'v. 责备 n. 责任' },
    { word: 'blast', meaning: 'n. 爆炸，一阵 v. 炸毁' },
    { word: 'bloom', meaning: 'n./v. 开花，繁盛' },
    { word: 'boost', meaning: 'v./n. 提升，增加' },
    { word: 'border', meaning: 'n. 边界 v. 接壤' },
    { word: 'bound', meaning: 'v. 跳跃 adj. 一定的' },
    { word: 'boundary', meaning: 'n. 分界线，范围' },
    { word: 'brilliant', meaning: 'adj. 光辉的，杰出的' },
    { word: 'budget', meaning: 'n. 预算 v. 做预算' },
    { word: 'burden', meaning: 'n. 负担 v. 使负重' },
    { word: 'burst', meaning: 'v./n. 爆发，破裂' },
    { word: 'calculate', meaning: 'v. 计算，估计' },
    { word: 'campaign', meaning: 'n. 运动，战役' },
    { word: 'cancel', meaning: 'v. 取消，撤销' },
    { word: 'candidate', meaning: 'n. 候选人' },
    { word: 'capable', meaning: 'adj. 有能力的' },
    { word: 'capacity', meaning: 'n. 容量，能力' },
    { word: 'capture', meaning: 'v. 捕获，夺取' },
    { word: 'career', meaning: 'n. 生涯，职业' },
    { word: 'catalog', meaning: 'n. 目录 v. 编目' },
    { word: 'category', meaning: 'n. 类别，种类' },
    { word: 'cause', meaning: 'n. 原因 v. 引起' },
    { word: 'caution', meaning: 'n. 谨慎 v. 警告' },
    { word: 'cease', meaning: 'v./n. 停止，终止' },
    { word: 'celebrate', meaning: 'v. 庆祝，赞美' },
    { word: 'challenge', meaning: 'n. 挑战 v. 质疑' },
    { word: 'champion', meaning: 'n. 冠军，拥护者' },
    { word: 'channel', meaning: 'n. 频道，渠道' },
    { word: 'chapter', meaning: 'n. 章节' },
    { word: 'character', meaning: 'n. 性格，角色' },
    { word: 'characteristic', meaning: 'adj. 典型的 n. 特征' },
    { word: 'charge', meaning: 'v. 收费 n. 费用' },
    { word: 'charity', meaning: 'n. 慈善，施舍' },
    { word: 'chart', meaning: 'n. 图表 v. 记录' },
    { word: 'chase', meaning: 'v./n. 追逐，追捕' },
    { word: 'chemical', meaning: 'adj. 化学的 n. 化学物质' },
    { word: 'circumstance', meaning: 'n. 环境，情况' },
    { word: 'citizen', meaning: 'n. 公民，市民' },
    { word: 'claim', meaning: 'v./n. 声称，要求' },
    { word: 'clarify', meaning: 'v. 澄清，阐明' },
    { word: 'classic', meaning: 'adj. 经典的 n. 名著' },
    { word: 'client', meaning: 'n. 客户，委托人' },
    { word: 'climate', meaning: 'n. 气候，风气' },
    { word: 'collapse', meaning: 'v./n. 倒塌，崩溃' },
    { word: 'colleague', meaning: 'n. 同事，同僚' },
    { word: 'command', meaning: 'v./n. 命令，指挥' },
    { word: 'comment', meaning: 'n./v. 评论，意见' },
    { word: 'commerce', meaning: 'n. 商业，贸易' },
    { word: 'commission', meaning: 'n. 委员会，佣金' },
    { word: 'commit', meaning: 'v. 犯（罪），承诺' },
    { word: 'communicate', meaning: 'v. 交流，传达' },
    { word: 'community', meaning: 'n. 社区，团体' },
    { word: 'companion', meaning: 'n. 伙伴，同伴' },
    { word: 'company', meaning: 'n. 公司，陪伴' },
    { word: 'compare', meaning: 'v. 比较，对比' },
    { word: 'compete', meaning: 'v. 竞争，比赛' },
    { word: 'competent', meaning: 'adj. 胜任的，有能力的' },
    { word: 'competition', meaning: 'n. 竞争，比赛' },
    { word: 'competitive', meaning: 'adj. 竞争的，有竞争力的' },
    { word: 'complain', meaning: 'v. 抱怨，投诉' },
    { word: 'complete', meaning: 'adj. 完全的 v. 完成' },
    { word: 'complex', meaning: 'adj. 复杂的，复合的' },
    { word: 'complicate', meaning: 'v. 使复杂化' },
    { word: 'component', meaning: 'n. 组成部分，成分' },
    { word: 'compose', meaning: 'v. 组成，创作' },
    { word: 'comprehend', meaning: 'v. 理解，领悟' },
    { word: 'comprehensive', meaning: 'adj. 全面的，综合的' },
    { word: 'concentrate', meaning: 'v. 集中，专注' },
    { word: 'concept', meaning: 'n. 概念，观念' },
    { word: 'concern', meaning: 'v./n. 涉及，关心' },
    { word: 'conclude', meaning: 'v. 得出结论，结束' },
    { word: 'conclusion', meaning: 'n. 结论，结尾' },
    { word: 'concrete', meaning: 'adj. 具体的 n. 混凝土' },
    { word: 'condition', meaning: 'n. 条件，状况' },
    { word: 'conduct', meaning: 'v. 指挥 n. 行为' },
    { word: 'conference', meaning: 'n. 会议，讨论会' },
    { word: 'confidence', meaning: 'n. 信心，自信' },
    { word: 'confident', meaning: 'adj. 自信的，确信的' },
    { word: 'confirm', meaning: 'v. 确认，证实' },
    { word: 'conflict', meaning: 'n./v. 冲突，矛盾' },
    { word: 'confuse', meaning: 'v. 使困惑，混淆' },
    { word: 'connect', meaning: 'v. 连接，联结' },
    { word: 'conscience', meaning: 'n. 良心，道德心' },
    { word: 'conscious', meaning: 'adj. 有意识的，刻意的' },
    { word: 'consequence', meaning: 'n. 结果，后果' },
    { word: 'conservation', meaning: 'n. 保护，保存' },
    { word: 'conservative', meaning: 'adj. 保守的 n. 保守者' },
    { word: 'considerable', meaning: 'adj. 相当大的，重要的' },
    { word: 'consistent', meaning: 'adj. 一致的，连贯的' },
    { word: 'constant', meaning: 'adj. 不断的，恒定的' },
    { word: 'construct', meaning: 'v. 建造，构建' },
    { word: 'consult', meaning: 'v. 咨询，查阅' },
    { word: 'consume', meaning: 'v. 消费，消耗' },
    { word: 'consumer', meaning: 'n. 消费者，用户' },
    { word: 'consumption', meaning: 'n. 消费，消耗量' },
    { word: 'contact', meaning: 'n./v. 接触，联系' },
    { word: 'contain', meaning: 'v. 包含，容纳' },
    { word: 'contemporary', meaning: 'adj. 当代的，同时代的' },
    { word: 'content', meaning: 'n. 内容 adj. 满足的' },
    { word: 'contest', meaning: 'n./v. 比赛，竞争' },
    { word: 'context', meaning: 'n. 背景，语境' },
    { word: 'contract', meaning: 'n. 合同 v. 收缩' },
    { word: 'contrast', meaning: 'n./v. 对比，差异' },
    { word: 'contribute', meaning: 'v. 贡献，投稿' },
    { word: 'contribution', meaning: 'n. 贡献，捐赠' },
    { word: 'controversy', meaning: 'n. 争议，辩论' },
    { word: 'convenient', meaning: 'adj. 方便的，便利的' },
    { word: 'convention', meaning: 'n. 惯例，大会' },
    { word: 'convince', meaning: 'v. 说服，使确信' },
    { word: 'cooperate', meaning: 'v. 合作，配合' },
    { word: 'cope', meaning: 'v. 应付，处理' },
    { word: 'core', meaning: 'n. 核心，要点' },
    { word: 'corporate', meaning: 'adj. 公司的，法人的' },
    { word: 'correct', meaning: 'adj. 正确的 v. 改正' },
    { word: 'correspond', meaning: 'v. 相符合，通信' },
    { word: 'council', meaning: 'n. 委员会，议会' },
    { word: 'county', meaning: 'n. 郡，县' },
    { word: 'couple', meaning: 'n. 一对，夫妇' },
    { word: 'courage', meaning: 'n. 勇气，胆量' },
    { word: 'course', meaning: 'n. 课程，过程' },
    { word: 'coverage', meaning: 'n. 覆盖范围，报道' },
    { word: 'crash', meaning: 'v./n. 碰撞，坠落' },
    { word: 'create', meaning: 'v. 创造，创建' },
    { word: 'creation', meaning: 'n. 创造，作品' },
    { word: 'creative', meaning: 'adj. 有创造力的' },
    { word: 'creature', meaning: 'n. 生物，动物' },
    { word: 'credit', meaning: 'n. 信用，学分' },
    { word: 'crime', meaning: 'n. 罪，犯罪' },
    { word: 'criminal', meaning: 'n. 罪犯 adj. 犯罪的' },
    { word: 'crisis', meaning: 'n. 危机，紧要关头' },
    { word: 'criteria', meaning: 'n. 标准，准则' },
    { word: 'critical', meaning: 'adj. 批评的，关键的' },
    { word: 'criticism', meaning: 'n. 批评，批判' },
    { word: 'crop', meaning: 'n. 庄稼 v. 剪短' },
    { word: 'crucial', meaning: 'adj. 至关重要的' },
    { word: 'cultivate', meaning: 'v. 培养，耕作' },
    { word: 'culture', meaning: 'n. 文化，文明' },
    { word: 'curiosity', meaning: 'n. 好奇心，求知欲' },
    { word: 'curious', meaning: 'adj. 好奇的，求知的' },
    { word: 'current', meaning: 'n. 水流 adj. 当前的' },
    { word: 'curriculum', meaning: 'n. 课程（总称）' },
    { word: 'custom', meaning: 'n. 习惯，风俗' },
    { word: 'customer', meaning: 'n. 顾客，客户' },
    { word: 'cycle', meaning: 'n. 循环 v. 骑自行车' },
    { word: 'damage', meaning: 'n./v. 损害，损坏' },
    { word: 'data', meaning: 'n. 数据，资料' },
    { word: 'database', meaning: 'n. 数据库' },
    { word: 'debate', meaning: 'n./v. 辩论，争论' },
    { word: 'debt', meaning: 'n. 债务，欠款' },
    { word: 'decade', meaning: 'n. 十年' },
    { word: 'decay', meaning: 'v./n. 腐烂，衰退' },
    { word: 'decent', meaning: 'adj. 像样的，体面的' },
    { word: 'decision', meaning: 'n. 决定，决策' },
    { word: 'declaration', meaning: 'n. 宣布，声明' },
    { word: 'decline', meaning: 'v./n. 下降，衰退' },
    { word: 'decorate', meaning: 'v. 装饰，装潢' },
    { word: 'decrease', meaning: 'v./n. 减少，降低' },
    { word: 'defeat', meaning: 'v./n. 打败，击败' },
    { word: 'defend', meaning: 'v. 防御，辩护' },
    { word: 'define', meaning: 'v. 定义，界定' },
    { word: 'definite', meaning: 'adj. 明确的，确定的' },
    { word: 'degree', meaning: 'n. 程度，学位' },
    { word: 'delay', meaning: 'v./n. 延迟，推迟' },
    { word: 'deliberate', meaning: 'adj. 故意的，深思熟虑的' },
    { word: 'delicate', meaning: 'adj. 微妙的，精致的' },
    { word: 'deliver', meaning: 'v. 递送，发表' },
    { word: 'delivery', meaning: 'n. 递送，交付' },
    { word: 'demand', meaning: 'n./v. 要求，需求' },
    { word: 'democracy', meaning: 'n. 民主，民主制度' },
    { word: 'demonstrate', meaning: 'v. 证明，示范' },
    { word: 'deny', meaning: 'v. 否认，拒绝' },
    { word: 'depart', meaning: 'v. 离开，出发' },
    { word: 'department', meaning: 'n. 部门，系' },
    { word: 'departure', meaning: 'n. 离开，启程' },
    { word: 'depend', meaning: 'v. 依靠，取决于' },
    { word: 'dependent', meaning: 'adj. 依赖的，从属的' },
    { word: 'deposit', meaning: 'v. 存放 n. 押金' },
    { word: 'depress', meaning: 'v. 使沮丧，压低' },
    { word: 'derive', meaning: 'v. 源于，获得' },
    { word: 'describe', meaning: 'v. 描述，形容' },
    { word: 'description', meaning: 'n. 描述，说明' },
    { word: 'desert', meaning: 'n. 沙漠 v. 遗弃' },
    { word: 'deserve', meaning: 'v. 应得，配得上' },
    { word: 'design', meaning: 'v./n. 设计，图案' },
    { word: 'desire', meaning: 'v./n. 渴望，欲望' },
    { word: 'desperate', meaning: 'adj. 绝望的，拼命的' },
    { word: 'despite', meaning: 'prep. 尽管，不管' },
    { word: 'destination', meaning: 'n. 目的地，终点' },
    { word: 'destroy', meaning: 'v. 破坏，毁灭' },
    { word: 'destruction', meaning: 'n. 破坏，毁灭' },
    { word: 'detail', meaning: 'n. 细节，详情' },
    { word: 'detect', meaning: 'v. 察觉，发现' },
    { word: 'determine', meaning: 'v. 决定，确定' },
    { word: 'develop', meaning: 'v. 发展，开发' },
    { word: 'device', meaning: 'n. 设备，装置' },
    { word: 'devote', meaning: 'v. 致力于，奉献' },
    { word: 'differ', meaning: 'v. 不同，相异' },
    { word: 'digest', meaning: 'v. 消化 n. 文摘' },
    { word: 'dignity', meaning: 'n. 尊严，高贵' },
    { word: 'dilemma', meaning: 'n. 困境，两难' },
    { word: 'dimension', meaning: 'n. 维度，方面' },
    { word: 'diminish', meaning: 'v. 减少，缩小' },
    { word: 'diplomatic', meaning: 'adj. 外交的，有手腕的' },
    { word: 'discipline', meaning: 'n. 纪律，学科' },
    { word: 'disclose', meaning: 'v. 揭露，透露' },
    { word: 'discount', meaning: 'n. 折扣 v. 打折' },
    { word: 'discourage', meaning: 'v. 使气馁，阻止' },
    { word: 'discover', meaning: 'v. 发现，发觉' },
    { word: 'discovery', meaning: 'n. 发现' },
    { word: 'discrimination', meaning: 'n. 歧视，辨别' },
    { word: 'discuss', meaning: 'v. 讨论，谈论' },
    { word: 'disease', meaning: 'n. 疾病' },
    { word: 'dismiss', meaning: 'v. 解雇，驳回' },
    { word: 'display', meaning: 'v./n. 展示，陈列' },
    { word: 'dispute', meaning: 'n./v. 争论，争执' },
    { word: 'dissolve', meaning: 'v. 溶解，解散' },
    { word: 'distance', meaning: 'n. 距离，远方' },
    { word: 'distant', meaning: 'adj. 遥远的，疏远的' },
    { word: 'distinct', meaning: 'adj. 不同的，明显的' },
    { word: 'distinction', meaning: 'n. 区别，差别' },
    { word: 'distinguish', meaning: 'v. 区分，辨别' },
    { word: 'distribute', meaning: 'v. 分配，分发' },
    { word: 'district', meaning: 'n. 地区，区域' },
    { word: 'diverse', meaning: 'adj. 多样的，不同的' },
    { word: 'diversity', meaning: 'n. 多样性' },
    { word: 'division', meaning: 'n. 分开，部门' },
    { word: 'document', meaning: 'n. 文件 v. 记录' },
    { word: 'domestic', meaning: 'adj. 国内的，家庭的' },
    { word: 'dominant', meaning: 'adj. 占优势的，主导的' },
    { word: 'dominate', meaning: 'v. 支配，主宰' },
    { word: 'donation', meaning: 'n. 捐赠，捐款' },
    { word: 'draft', meaning: 'n. 草稿 v. 起草' },
    { word: 'drain', meaning: 'v. 排干 n. 下水道' },
    { word: 'drama', meaning: 'n. 戏剧，剧本' },
    { word: 'dramatic', meaning: 'adj. 戏剧性的，巨大的' },
    { word: 'drastic', meaning: 'adj. 激烈的，猛烈的' },
    { word: 'due', meaning: 'adj. 到期的，应得的' },
    { word: 'durable', meaning: 'adj. 耐用的，持久的' },
    { word: 'dynamic', meaning: 'adj. 动态的，有活力的' },
  ],
  cet6: [
    { word: 'abbreviation', meaning: 'n. 缩写' },
    { word: 'abide', meaning: 'v. 遵守，忍受' },
    { word: 'absurd', meaning: 'adj. 荒谬的，可笑的' },
    { word: 'abundance', meaning: 'n. 丰富，充裕' },
    { word: 'accessible', meaning: 'adj. 易接近的，可理解的' },
    { word: 'acclaim', meaning: 'v./n. 欢呼，称赞' },
    { word: 'acquaintance', meaning: 'n. 熟人，相识' },
    { word: 'acquisition', meaning: 'n. 获得，购得物' },
    { word: 'acute', meaning: 'adj. 严重的，敏锐的' },
    { word: 'adverse', meaning: 'adj. 不利的，敌对的' },
    { word: 'advocate', meaning: 'v. 提倡 n. 拥护者' },
    { word: 'aggregate', meaning: 'v./n. 合计，聚合体' },
    { word: 'allege', meaning: 'v. 断言，宣称' },
    { word: 'alliance', meaning: 'n. 联盟，结盟' },
    { word: 'allocate', meaning: 'v. 分配，拨出' },
    { word: 'alleviate', meaning: 'v. 缓解，减轻' },
    { word: 'ambiguous', meaning: 'adj. 模糊不清的' },
    { word: 'amend', meaning: 'v. 修改，修正' },
    { word: 'ample', meaning: 'adj. 充足的，宽敞的' },
    { word: 'analogy', meaning: 'n. 类比，比拟' },
    { word: 'anonymous', meaning: 'adj. 匿名的' },
    { word: 'anticipate', meaning: 'v. 预期，提前考虑' },
    { word: 'apparatus', meaning: 'n. 仪器，设备' },
    { word: 'appease', meaning: 'v. 安抚，缓和' },
    { word: 'arbitrary', meaning: 'adj. 随意的，武断的' },
    { word: 'articulate', meaning: 'adj. 善于表达的 v. 清晰表达' },
    { word: 'ascertain', meaning: 'v. 查明，确定' },
    { word: 'aspiration', meaning: 'n. 志向，渴望' },
    { word: 'assassinate', meaning: 'v. 暗杀，行刺' },
    { word: 'assemble', meaning: 'v. 集合，组装' },
    { word: 'assert', meaning: 'v. 断言，坚持' },
    { word: 'assess', meaning: 'v. 评估，评定' },
    { word: 'asset', meaning: 'n. 资产，财产' },
    { word: 'assimilate', meaning: 'v. 同化，吸收' },
    { word: 'assumption', meaning: 'n. 假设，承担' },
    { word: 'assurance', meaning: 'n. 保证，把握' },
    { word: 'attendance', meaning: 'n. 出席，出勤' },
    { word: 'attribute', meaning: 'v. 归因于 n. 属性' },
    { word: 'audit', meaning: 'v./n. 审计，审核' },
    { word: 'authentic', meaning: 'adj. 真实的，可信的' },
    { word: 'authorize', meaning: 'v. 授权，批准' },
    { word: 'automate', meaning: 'v. 使自动化' },
    { word: 'autonomous', meaning: 'adj. 自治的，自主的' },
    { word: 'avail', meaning: 'v. 有助于 n. 效用' },
    { word: 'awareness', meaning: 'n. 意识，认识' },
    { word: 'barren', meaning: 'adj. 贫瘠的，荒芜的' },
    { word: 'betray', meaning: 'v. 背叛，泄露' },
    { word: 'bias', meaning: 'n. 偏见，倾向' },
    { word: 'bibliography', meaning: 'n. 参考书目' },
    { word: 'bid', meaning: 'v./n. 出价，投标' },
    { word: 'bizarre', meaning: 'adj. 奇异的，怪诞的' },
    { word: 'boom', meaning: 'v./n. 繁荣，暴涨' },
    { word: 'boycott', meaning: 'v./n. 联合抵制' },
    { word: 'breach', meaning: 'n./v. 违反，破坏' },
    { word: 'bulk', meaning: 'n. 体积，大部分' },
    { word: 'bureaucracy', meaning: 'n. 官僚机构' },
    { word: 'capable', meaning: 'adj. 有能力的' },
    { word: 'capsule', meaning: 'n. 胶囊，航天舱' },
    { word: 'casualty', meaning: 'n. 伤亡者，事故受害者' },
    { word: 'catalogue', meaning: 'n. 目录 v. 编入目录' },
    { word: 'catastrophe', meaning: 'n. 灾难，大祸' },
    { word: 'caution', meaning: 'n. 谨慎 v. 警告' },
    { word: 'censor', meaning: 'v. 审查 n. 审查员' },
    { word: 'chronic', meaning: 'adj. 慢性的，长期的' },
    { word: 'circuit', meaning: 'n. 电路，环路' },
    { word: 'circular', meaning: 'adj. 循环的，圆形的' },
    { word: 'civilian', meaning: 'n. 平民 adj. 民用的' },
    { word: 'clarify', meaning: 'v. 澄清，说明' },
    { word: 'clash', meaning: 'v./n. 冲突，抵触' },
    { word: 'clause', meaning: 'n. 条款，从句' },
    { word: 'coalition', meaning: 'n. 联合，联盟' },
    { word: 'cognitive', meaning: 'adj. 认知的' },
    { word: 'coherent', meaning: 'adj. 连贯的，一致的' },
    { word: 'coincide', meaning: 'v. 同时发生，相符' },
    { word: 'collaborate', meaning: 'v. 合作，协作' },
    { word: 'collide', meaning: 'v. 碰撞，冲突' },
    { word: 'commemorate', meaning: 'v. 纪念，庆祝' },
    { word: 'commence', meaning: 'v. 开始' },
    { word: 'commodity', meaning: 'n. 商品，日用品' },
    { word: 'commonplace', meaning: 'adj. 平凡的 n. 平常事' },
    { word: 'compensate', meaning: 'v. 补偿，赔偿' },
    { word: 'compile', meaning: 'v. 汇编，编纂' },
    { word: 'complement', meaning: 'v. 补充，衬托 n. 补足物' },
    { word: 'complication', meaning: 'n. 复杂化，并发症' },
    { word: 'comply', meaning: 'v. 遵守，顺从' },
    { word: 'compound', meaning: 'n. 化合物 adj. 复合的' },
    { word: 'compulsory', meaning: 'adj. 强制性的，义务的' },
    { word: 'concede', meaning: 'v. 承认（失败），让步' },
    { word: 'conceive', meaning: 'v. 设想，怀孕' },
    { word: 'conception', meaning: 'n. 概念，构想' },
    { word: 'concession', meaning: 'n. 让步，特许权' },
    { word: 'confer', meaning: 'v. 商谈，授予' },
    { word: 'configuration', meaning: 'n. 配置，布局' },
    { word: 'confine', meaning: 'v. 限制，禁闭' },
    { word: 'conform', meaning: 'v. 遵从，符合' },
    { word: 'confront', meaning: 'v. 面对，对抗' },
    { word: 'conscientious', meaning: 'adj. 认真的，尽责的' },
    { word: 'consecutive', meaning: 'adj. 连续的' },
    { word: 'consensus', meaning: 'n. 共识，一致意见' },
    { word: 'conserve', meaning: 'v. 保护，节约' },
    { word: 'consolidate', meaning: 'v. 巩固，合并' },
    { word: 'conspicuous', meaning: 'adj. 显眼的，引人注目的' },
    { word: 'constituent', meaning: 'n. 成分 adj. 构成的' },
    { word: 'constitute', meaning: 'v. 构成，建立' },
    { word: 'constrain', meaning: 'v. 约束，限制' },
    { word: 'consult', meaning: 'v. 咨询，查阅' },
    { word: 'contaminate', meaning: 'v. 污染，弄脏' },
    { word: 'contemplate', meaning: 'v. 沉思，考虑' },
    { word: 'contend', meaning: 'v. 竞争，声称' },
    { word: 'contradict', meaning: 'v. 反驳，与…矛盾' },
    { word: 'controversy', meaning: 'n. 争议，辩论' },
    { word: 'convene', meaning: 'v. 召集，集合' },
    { word: 'converge', meaning: 'v. 汇聚，集中' },
    { word: 'convert', meaning: 'v. 转化，改变信仰' },
    { word: 'convict', meaning: 'v. 定罪 n. 囚犯' },
    { word: 'conviction', meaning: 'n. 定罪，信念' },
    { word: 'cooperate', meaning: 'v. 合作，协作' },
    { word: 'coordinate', meaning: 'v. 协调 adj. 同等的' },
    { word: 'correlate', meaning: 'v. 使相互关联' },
    { word: 'corrode', meaning: 'v. 腐蚀，侵蚀' },
    { word: 'counterpart', meaning: 'n. 对应的人或物' },
    { word: 'courtesy', meaning: 'n. 礼貌，好意' },
    { word: 'criterion', meaning: 'n. 标准，准则' },
    { word: 'crucial', meaning: 'adj. 至关重要的' },
    { word: 'cultivate', meaning: 'v. 培养，耕种' },
    { word: 'cumulative', meaning: 'adj. 累积的' },
    { word: 'curriculum', meaning: 'n. 课程（总称）' },
    { word: 'database', meaning: 'n. 数据库' },
    { word: 'dazzle', meaning: 'v. 目眩，使惊奇' },
    { word: 'deadline', meaning: 'n. 截止日期' },
    { word: 'debate', meaning: 'n./v. 辩论，讨论' },
    { word: 'debris', meaning: 'n. 碎片，残骸' },
    { word: 'deceive', meaning: 'v. 欺骗，蒙蔽' },
    { word: 'decent', meaning: 'adj. 像样的，体面的' },
    { word: 'decisive', meaning: 'adj. 决定性的，果断的' },
    { word: 'declaration', meaning: 'n. 宣布，声明' },
    { word: 'decorate', meaning: 'v. 装饰，装点' },
    { word: 'decree', meaning: 'n. 法令 v. 颁布' },
    { word: 'dedicate', meaning: 'v. 致力于，献身' },
    { word: 'deduce', meaning: 'v. 推断，演绎' },
    { word: 'deem', meaning: 'v. 认为，视为' },
    { word: 'default', meaning: 'n./v. 违约，默认值' },
    { word: 'defect', meaning: 'n. 缺陷 v. 叛逃' },
    { word: 'deficit', meaning: 'n. 赤字，不足额' },
    { word: 'defy', meaning: 'v. 违抗，蔑视' },
    { word: 'degenerate', meaning: 'v. 退化 adj. 堕落的' },
    { word: 'delegate', meaning: 'n. 代表 v. 委派' },
    { word: 'deliberate', meaning: 'adj. 故意的，深思熟虑的' },
    { word: 'demographic', meaning: 'adj. 人口统计的' },
    { word: 'demonstrate', meaning: 'v. 证明，展示' },
    { word: 'denote', meaning: 'v. 表示，意味着' },
    { word: 'denounce', meaning: 'v. 谴责，揭发' },
    { word: 'depict', meaning: 'v. 描绘，描述' },
    { word: 'deploy', meaning: 'v. 部署，调度' },
    { word: 'depreciate', meaning: 'v. 贬值，贬低' },
    { word: 'deprive', meaning: 'v. 剥夺，使丧失' },
    { word: 'derive', meaning: 'v. 得到，源于' },
    { word: 'descend', meaning: 'v. 下降，遗传' },
    { word: 'designate', meaning: 'v. 指定，任命' },
    { word: 'deteriorate', meaning: 'v. 恶化，退化' },
    { word: 'diagnosis', meaning: 'n. 诊断' },
    { word: 'differentiate', meaning: 'v. 区分，区别' },
    { word: 'diffuse', meaning: 'v. 扩散 adj. 散漫的' },
    { word: 'dilemma', meaning: 'n. 困境，两难' },
    { word: 'diligent', meaning: 'adj. 勤奋的，勤勉的' },
    { word: 'diminish', meaning: 'v. 减少，贬低' },
    { word: 'diploma', meaning: 'n. 毕业文凭' },
    { word: 'diplomatic', meaning: 'adj. 外交的，老练的' },
    { word: 'discard', meaning: 'v. 丢弃，抛弃' },
    { word: 'discipline', meaning: 'n. 纪律，学科' },
    { word: 'disclose', meaning: 'v. 揭露，透露' },
    { word: 'discount', meaning: 'n. 折扣 v. 打折' },
    { word: 'discrepancy', meaning: 'n. 差异，不符' },
    { word: 'discriminate', meaning: 'v. 区分，歧视' },
    { word: 'disperse', meaning: 'v. 分散，散开' },
    { word: 'displace', meaning: 'v. 取代，迫使离开' },
    { word: 'disposal', meaning: 'n. 处理，处置' },
    { word: 'dispute', meaning: 'n./v. 争论，争议' },
    { word: 'disregard', meaning: 'v./n. 忽视，漠视' },
    { word: 'dissolve', meaning: 'v. 溶解，解散' },
    { word: 'distinctive', meaning: 'adj. 独特的，有特色的' },
    { word: 'distort', meaning: 'v. 扭曲，歪曲' },
    { word: 'distract', meaning: 'v. 分散注意力' },
    { word: 'diverge', meaning: 'v. 分叉，分歧' },
    { word: 'diverse', meaning: 'adj. 多样的，不同的' },
    { word: 'diversify', meaning: 'v. 使多样化' },
    { word: 'doctrine', meaning: 'n. 教条，主义' },
    { word: 'domain', meaning: 'n. 领域，领土' },
    { word: 'domestic', meaning: 'adj. 国内的，家庭的' },
    { word: 'dominant', meaning: 'adj. 主导的，占优势的' },
    { word: 'dominate', meaning: 'v. 支配，主宰' },
    { word: 'draft', meaning: 'n. 草稿 v. 起草' },
    { word: 'drought', meaning: 'n. 干旱，旱灾' },
    { word: 'dual', meaning: 'adj. 双重的，双的' },
    { word: 'dubious', meaning: 'adj. 可疑的，不确定的' },
    { word: 'duplicate', meaning: 'v. 复制 n. 副本' },
    { word: 'dwell', meaning: 'v. 居住，细想' },
    { word: 'dynamic', meaning: 'adj. 动态的，有活力的' },
    { word: 'elaborate', meaning: 'adj. 详尽的 v. 详细说明' },
    { word: 'elegant', meaning: 'adj. 优雅的，精美的' },
    { word: 'eliminate', meaning: 'v. 消除，淘汰' },
    { word: 'elite', meaning: 'n. 精英，上层人士' },
    { word: 'eloquent', meaning: 'adj. 雄辩的，有口才的' },
    { word: 'embrace', meaning: 'v. 拥抱，包含' },
    { word: 'emerge', meaning: 'v. 浮现，显现' },
    { word: 'emphasis', meaning: 'n. 强调，重点' },
    { word: 'encounter', meaning: 'v./n. 遭遇，邂逅' },
    { word: 'endeavor', meaning: 'v./n. 努力，尝试' },
    { word: 'enforce', meaning: 'v. 实施，强制执行' },
    { word: 'engage', meaning: 'v. 吸引，从事' },
    { word: 'enhance', meaning: 'v. 增强，提高' },
    { word: 'enormous', meaning: 'adj. 巨大的，庞大的' },
    { word: 'enthusiasm', meaning: 'n. 热情，热忱' },
    { word: 'entrepreneur', meaning: 'n. 企业家' },
    { word: 'envision', meaning: 'v. 展望，想象' },
    { word: 'epidemic', meaning: 'n. 流行病 adj. 流行性的' },
    { word: 'episode', meaning: 'n. 插曲，一段经历' },
    { word: 'equip', meaning: 'v. 装备，配备' },
    { word: 'equivalent', meaning: 'adj. 等价的 n. 等价物' },
    { word: 'erode', meaning: 'v. 侵蚀，削弱' },
    { word: 'essence', meaning: 'n. 本质，精华' },
    { word: 'establish', meaning: 'v. 建立，确立' },
    { word: 'estate', meaning: 'n. 房地产，财产' },
    { word: 'eternal', meaning: 'adj. 永恒的，永久的' },
    { word: 'ethical', meaning: 'adj. 伦理的，道德的' },
    { word: 'evaluate', meaning: 'v. 评估，评价' },
    { word: 'evoke', meaning: 'v. 唤起，引发' },
    { word: 'exaggerate', meaning: 'v. 夸张，夸大' },
    { word: 'exceed', meaning: 'v. 超过，超越' },
    { word: 'excellent', meaning: 'adj. 优秀的，卓越的' },
    { word: 'exception', meaning: 'n. 例外，除外' },
    { word: 'excess', meaning: 'n. 过度 adj. 额外的' },
    { word: 'execute', meaning: 'v. 执行，处决' },
    { word: 'exemplify', meaning: 'v. 例证，作为…例子' },
    { word: 'exert', meaning: 'v. 施加，运用' },
    { word: 'exhaust', meaning: 'v. 耗尽 n. 排气' },
    { word: 'exhibit', meaning: 'v. 展览 n. 展品' },
    { word: 'expand', meaning: 'v. 扩大，膨胀' },
    { word: 'expedition', meaning: 'n. 远征，探险' },
    { word: 'expenditure', meaning: 'n. 支出，花费' },
    { word: 'expertise', meaning: 'n. 专长，专业知识' },
    { word: 'explicit', meaning: 'adj. 明确的，露骨的' },
    { word: 'exploit', meaning: 'v. 利用，剥削' },
    { word: 'explore', meaning: 'v. 探索，考察' },
    { word: 'expose', meaning: 'v. 暴露，揭露' },
    { word: 'extend', meaning: 'v. 延伸，扩展' },
    { word: 'extensive', meaning: 'adj. 广泛的，大量的' },
    { word: 'extent', meaning: 'n. 程度，范围' },
    { word: 'external', meaning: 'adj. 外部的，对外的' },
    { word: 'extract', meaning: 'v. 提取 n. 摘录' },
    { word: 'extreme', meaning: 'adj. 极端的 n. 极端' },
  ],
  ielts: [
    { word: 'abandonment', meaning: 'n. 抛弃，自暴自弃' },
    { word: 'aberration', meaning: 'n. 反常，异常' },
    { word: 'abhor', meaning: 'v. 憎恶，痛恨' },
    { word: 'aboriginal', meaning: 'adj. 土著的，原始的' },
    { word: 'abound', meaning: 'v. 富于，充满' },
    { word: 'abrasive', meaning: 'adj. 粗糙的，生硬的' },
    { word: 'abridge', meaning: 'v. 删节，缩短' },
    { word: 'abstain', meaning: 'v. 戒除，弃权' },
    { word: 'academician', meaning: 'n. 院士，学者' },
    { word: 'accentuate', meaning: 'v. 强调，突出' },
    { word: 'accessible', meaning: 'adj. 易获得的，易接近的' },
    { word: 'accommodating', meaning: 'adj. 乐于助人的，随和的' },
    { word: 'accountability', meaning: 'n. 问责，责任' },
    { word: 'accumulate', meaning: 'v. 积累，积聚' },
    { word: 'acquisition', meaning: 'n. 获得，习得' },
    { word: 'adaptability', meaning: 'n. 适应性' },
    { word: 'adherent', meaning: 'n. 支持者，拥护者' },
    { word: 'administer', meaning: 'v. 管理，执行' },
    { word: 'adolescent', meaning: 'n. 青少年 adj. 青春期的' },
    { word: 'adversary', meaning: 'n. 对手，敌手' },
    { word: 'adversity', meaning: 'n. 逆境，不幸' },
    { word: 'aesthetic', meaning: 'adj./n. 审美的，美感' },
    { word: 'affection', meaning: 'n. 感情，喜爱' },
    { word: 'affiliate', meaning: 'v. 使隶属 n. 分公司' },
    { word: 'aggregate', meaning: 'adj./n. 总计的，总量' },
    { word: 'aggression', meaning: 'n. 侵略，攻击' },
    { word: 'algorithm', meaning: 'n. 算法' },
    { word: 'alienate', meaning: 'v. 疏远，使不友好' },
    { word: 'allegation', meaning: 'n. 断言，指控' },
    { word: 'allocate', meaning: 'v. 分配，拨出' },
    { word: 'altruistic', meaning: 'adj. 利他的，无私的' },
    { word: 'ambiguity', meaning: 'n. 模糊，歧义' },
    { word: 'amend', meaning: 'v. 修改，修正' },
    { word: 'ample', meaning: 'adj. 充足的，宽敞的' },
    { word: 'analogy', meaning: 'n. 类比，类似' },
    { word: 'anchor', meaning: 'n. 锚 v. 固定，主持' },
    { word: 'anecdote', meaning: 'n. 轶事，趣闻' },
    { word: 'animation', meaning: 'n. 动画，活力' },
    { word: 'anomaly', meaning: 'n. 异常现象' },
    { word: 'anthropology', meaning: 'n. 人类学' },
    { word: 'appraisal', meaning: 'n. 评价，估价' },
    { word: 'apprentice', meaning: 'n. 学徒 v. 当学徒' },
    { word: 'appropriate', meaning: 'adj. 适当的 v. 拨款' },
    { word: 'arable', meaning: 'adj. 可耕作的' },
    { word: 'arbitrary', meaning: 'adj. 随意的，武断的' },
    { word: 'archaeology', meaning: 'n. 考古学' },
    { word: 'arid', meaning: 'adj. 干旱的，枯燥的' },
    { word: 'articulate', meaning: 'adj. 善于表达的 v. 清楚表达' },
    { word: 'artisan', meaning: 'n. 工匠，手艺人' },
    { word: 'ascertain', meaning: 'v. 查明，弄清' },
    { word: 'aspiration', meaning: 'n. 抱负，渴望' },
    { word: 'assertive', meaning: 'adj. 坚定自信的' },
    { word: 'assessment', meaning: 'n. 评估，评定' },
    { word: 'assumption', meaning: 'n. 假设，承担' },
    { word: 'asylum', meaning: 'n. 庇护，政治避难' },
    { word: 'atlas', meaning: 'n. 地图册' },
    { word: 'atmosphere', meaning: 'n. 大气，氛围' },
    { word: 'attainment', meaning: 'n. 达成，成就' },
    { word: 'authenticity', meaning: 'n. 真实性，可靠性' },
    { word: 'authority', meaning: 'n. 权威，当局' },
    { word: 'autonomous', meaning: 'adj. 自治的，自主的' },
    { word: 'autonomy', meaning: 'n. 自治，自主权' },
    { word: 'avalanche', meaning: 'n. 雪崩 v. 大量涌来' },
    { word: 'averse', meaning: 'adj. 反对的，厌恶的' },
    { word: 'bachelor', meaning: 'n. 学士，单身汉' },
    { word: 'bacterial', meaning: 'adj. 细菌的' },
    { word: 'bailiff', meaning: 'n. 法警，执行官' },
    { word: 'balance', meaning: 'n./v. 平衡，余额' },
    { word: 'bamboo', meaning: 'n. 竹子' },
    { word: 'bankruptcy', meaning: 'n. 破产' },
    { word: 'bargain', meaning: 'n. 廉价品 v. 讨价还价' },
    { word: 'barometer', meaning: 'n. 晴雨表，指标' },
    { word: 'barrier', meaning: 'n. 障碍，屏障' },
    { word: 'battery', meaning: 'n. 电池，一组' },
    { word: 'beam', meaning: 'n. 光束 v. 微笑' },
    { word: 'benchmark', meaning: 'n. 基准，参照标准' },
    { word: 'beneficial', meaning: 'adj. 有益的，有利的' },
    { word: 'beverage', meaning: 'n. 饮料' },
    { word: 'bilingual', meaning: 'adj. 双语的' },
    { word: 'biodiversity', meaning: 'n. 生物多样性' },
    { word: 'biography', meaning: 'n. 传记' },
    { word: 'blossom', meaning: 'n./v. 花开，繁荣' },
    { word: 'blueprint', meaning: 'n. 蓝图，计划' },
    { word: 'booming', meaning: 'adj. 繁荣的，迅速发展的' },
    { word: 'botanical', meaning: 'adj. 植物学的' },
    { word: 'boundary', meaning: 'n. 边界，分界线' },
    { word: 'bracket', meaning: 'n. 括号 v. 归类' },
    { word: 'breadwinner', meaning: 'n. 养家糊口的人' },
    { word: 'breakthrough', meaning: 'n. 突破，重大发现' },
    { word: 'brew', meaning: 'v. 酿造 n. 饮料' },
    { word: 'brink', meaning: 'n. 边缘，边缘状态' },
    { word: 'brochure', meaning: 'n. 小册子' },
    { word: 'bronze', meaning: 'n. 青铜，铜牌' },
    { word: 'bruise', meaning: 'n. 瘀伤 v. 碰伤' },
    { word: 'brutal', meaning: 'adj. 残忍的，野蛮的' },
    { word: 'budget', meaning: 'n. 预算 v. 安排' },
    { word: 'buffer', meaning: 'n. 缓冲物 v. 缓冲' },
    { word: 'bulletin', meaning: 'n. 公告，简报' },
    { word: 'bureaucracy', meaning: 'n. 官僚主义' },
    { word: 'cabinet', meaning: 'n. 内阁，储藏柜' },
    { word: 'calcium', meaning: 'n. 钙' },
    { word: 'calibrate', meaning: 'v. 校准，标定' },
    { word: 'campaign', meaning: 'n. 运动，战役' },
    { word: 'campus', meaning: 'n. 校园' },
    { word: 'candidacy', meaning: 'n. 候选资格' },
    { word: 'canteen', meaning: 'n. 食堂，餐厅' },
    { word: 'capacity', meaning: 'n. 容量，能力' },
    { word: 'capitalism', meaning: 'n. 资本主义' },
    { word: 'captive', meaning: 'n. 俘虏 adj. 被俘的' },
    { word: 'carbon', meaning: 'n. 碳' },
    { word: 'carnivore', meaning: 'n. 食肉动物' },
    { word: 'cartography', meaning: 'n. 制图学' },
    { word: 'catastrophe', meaning: 'n. 大灾难' },
    { word: 'categorize', meaning: 'v. 分类，归类' },
    { word: 'cater', meaning: 'v. 提供饮食，迎合' },
    { word: 'caution', meaning: 'n. 谨慎 v. 警告' },
    { word: 'census', meaning: 'n. 人口普查' },
    { word: 'ceramic', meaning: 'adj. 陶瓷的 n. 陶瓷' },
    { word: 'cereal', meaning: 'n. 谷物，麦片' },
    { word: 'certificate', meaning: 'n. 证书，执照' },
    { word: 'chancellor', meaning: 'n. 总理，校长' },
    { word: 'chronicle', meaning: 'n. 编年史 v. 记载' },
    { word: 'circulation', meaning: 'n. 循环，发行量' },
    { word: 'circumstance', meaning: 'n. 环境，情况' },
    { word: 'citizenship', meaning: 'n. 公民身份' },
    { word: 'civic', meaning: 'adj. 市民的，公民的' },
    { word: 'civilization', meaning: 'n. 文明' },
    { word: 'clarify', meaning: 'v. 澄清，阐明' },
    { word: 'classify', meaning: 'v. 分类，归类' },
    { word: 'clergy', meaning: 'n. 神职人员' },
    { word: 'climate', meaning: 'n. 气候，风气' },
    { word: 'cluster', meaning: 'n. 群 v. 聚集' },
    { word: 'coalition', meaning: 'n. 联合，联盟' },
    { word: 'coastal', meaning: 'adj. 沿海的，海岸的' },
    { word: 'cognitive', meaning: 'adj. 认知的' },
    { word: 'coherent', meaning: 'adj. 连贯的，有条理的' },
    { word: 'cohesion', meaning: 'n. 凝聚力，连贯性' },
    { word: 'coincidence', meaning: 'n. 巧合，一致' },
    { word: 'collaboration', meaning: 'n. 合作，协作' },
    { word: 'collision', meaning: 'n. 碰撞，冲突' },
    { word: 'colonize', meaning: 'v. 殖民，开拓殖民地' },
    { word: 'commemorate', meaning: 'v. 纪念' },
    { word: 'commence', meaning: 'v. 开始' },
    { word: 'commerce', meaning: 'n. 商业，贸易' },
    { word: 'commodity', meaning: 'n. 商品' },
    { word: 'communal', meaning: 'adj. 公共的，社区的' },
    { word: 'compatible', meaning: 'adj. 兼容的，和睦的' },
    { word: 'compensate', meaning: 'v. 补偿，弥补' },
    { word: 'competence', meaning: 'n. 能力，胜任' },
    { word: 'compile', meaning: 'v. 汇编，编纂' },
    { word: 'complement', meaning: 'v./n. 补充，补足' },
    { word: 'complexity', meaning: 'n. 复杂性' },
    { word: 'compliance', meaning: 'n. 遵守，服从' },
    { word: 'component', meaning: 'n. 成分，组件' },
    { word: 'comprehensive', meaning: 'adj. 全面的，综合的' },
    { word: 'compulsory', meaning: 'adj. 强制性的' },
    { word: 'conceal', meaning: 'v. 隐藏，隐瞒' },
    { word: 'concentrate', meaning: 'v. 集中，专注' },
    { word: 'conception', meaning: 'n. 概念，构想' },
    { word: 'concession', meaning: 'n. 让步，妥协' },
    { word: 'concrete', meaning: 'adj. 具体的 n. 混凝土' },
    { word: 'condemn', meaning: 'v. 谴责，判刑' },
    { word: 'conduct', meaning: 'v./n. 行为，引导' },
    { word: 'confine', meaning: 'v. 限制，局限' },
    { word: 'conform', meaning: 'v. 遵守，符合' },
    { word: 'confront', meaning: 'v. 面对，对抗' },
    { word: 'consciousness', meaning: 'n. 意识，知觉' },
    { word: 'consecutive', meaning: 'adj. 连续的' },
    { word: 'consensus', meaning: 'n. 一致意见' },
    { word: 'consent', meaning: 'n./v. 同意，允许' },
    { word: 'consequence', meaning: 'n. 结果，后果' },
    { word: 'conservation', meaning: 'n. 保护，节约' },
    { word: 'considerable', meaning: 'adj. 相当大的' },
    { word: 'consist', meaning: 'v. 由…组成' },
    { word: 'consolidate', meaning: 'v. 巩固，合并' },
    { word: 'conspicuous', meaning: 'adj. 显著的' },
    { word: 'constitute', meaning: 'v. 构成，建立' },
    { word: 'consult', meaning: 'v. 咨询，查阅' },
    { word: 'consume', meaning: 'v. 消费，消耗' },
    { word: 'contemporary', meaning: 'adj. 当代的，同时代的' },
    { word: 'contradict', meaning: 'v. 反驳，矛盾' },
    { word: 'contribute', meaning: 'v. 贡献，捐献' },
    { word: 'controversial', meaning: 'adj. 有争议的' },
    { word: 'convenience', meaning: 'n. 方便，便利' },
    { word: 'conventional', meaning: 'adj. 传统的，惯例的' },
    { word: 'converge', meaning: 'v. 汇聚，集中' },
    { word: 'conversely', meaning: 'adv. 相反地' },
    { word: 'convert', meaning: 'v. 转化，转变' },
    { word: 'conviction', meaning: 'n. 信念，定罪' },
    { word: 'coordinate', meaning: 'v. 协调 n. 坐标' },
    { word: 'copyright', meaning: 'n. 版权，著作权' },
    { word: 'correlate', meaning: 'v. 相关，关联' },
    { word: 'corroborate', meaning: 'v. 证实，支持' },
    { word: 'counsel', meaning: 'n./v. 建议，法律顾问' },
    { word: 'credential', meaning: 'n. 凭证，证书' },
    { word: 'credibility', meaning: 'n. 可信度' },
    { word: 'criterion', meaning: 'n. 标准，准则' },
    { word: 'critical', meaning: 'adj. 批评的，关键的' },
    { word: 'criticism', meaning: 'n. 批评，评论' },
    { word: 'crucial', meaning: 'adj. 至关重要的' },
    { word: 'cultivate', meaning: 'v. 培养，耕种' },
    { word: 'cultural immersion', meaning: 'n. 文化沉浸' },
    { word: 'cumulative', meaning: 'adj. 累积的' },
    { word: 'curriculum', meaning: 'n. 课程（总称）' },
    { word: 'customs', meaning: 'n. 海关，关税' },
    { word: 'cyberspace', meaning: 'n. 网络空间' },
    { word: 'database', meaning: 'n. 数据库' },
    { word: 'debate', meaning: 'n./v. 辩论，讨论' },
    { word: 'debris', meaning: 'n. 残骸，碎片' },
    { word: 'decent', meaning: 'adj. 体面的，像样的' },
    { word: 'decisive', meaning: 'adj. 果断的，决定性的' },
    { word: 'decline', meaning: 'v./n. 下降，衰退' },
    { word: 'decoration', meaning: 'n. 装饰，装潢' },
    { word: 'decrease', meaning: 'v./n. 减少，降低' },
    { word: 'dedicate', meaning: 'v. 致力于，献身' },
    { word: 'deficiency', meaning: 'n. 缺乏，缺陷' },
    { word: 'deficit', meaning: 'n. 赤字，不足' },
    { word: 'deforestation', meaning: 'n. 森林砍伐' },
    { word: 'degradation', meaning: 'n. 恶化，降解' },
    { word: 'delegate', meaning: 'n. 代表 v. 委派' },
    { word: 'deliberate', meaning: 'adj. 故意的，深思熟虑的' },
    { word: 'demographic', meaning: 'adj. 人口统计的' },
    { word: 'demonstrate', meaning: 'v. 证明，示范' },
    { word: 'density', meaning: 'n. 密度' },
    { word: 'depict', meaning: 'v. 描绘，描述' },
    { word: 'deposit', meaning: 'v./n. 存放，押金' },
    { word: 'deprive', meaning: 'v. 剥夺，使丧失' },
    { word: 'deprived', meaning: 'adj. 贫困的，匮乏的' },
    { word: 'derive', meaning: 'v. 源自，获取' },
    { word: 'designate', meaning: 'v. 指定，命名' },
    { word: 'deteriorate', meaning: 'v. 恶化，退化' },
    { word: 'determination', meaning: 'n. 决心，决定' },
    { word: 'deterrent', meaning: 'n. 威慑物，遏制因素' },
    { word: 'detrimental', meaning: 'adj. 有害的，不利的' },
    { word: 'devastate', meaning: 'v. 毁坏，使震惊' },
    { word: 'diagnose', meaning: 'v. 诊断' },
    { word: 'differentiate', meaning: 'v. 区分，区别' },
    { word: 'dilemma', meaning: 'n. 困境，两难' },
    { word: 'dimension', meaning: 'n. 维度，方面' },
    { word: 'diminish', meaning: 'v. 减少，缩小' },
    { word: 'diplomacy', meaning: 'n. 外交，手段' },
    { word: 'discipline', meaning: 'n. 纪律，学科' },
    { word: 'disclose', meaning: 'v. 揭露，公开' },
    { word: 'discount', meaning: 'n./v. 折扣，打折' },
    { word: 'discrepancy', meaning: 'n. 差异，不符' },
    { word: 'discrimination', meaning: 'n. 歧视，辨别' },
    { word: 'disparity', meaning: 'n. 差异，不平等' },
    { word: 'disperse', meaning: 'v. 分散，散开' },
    { word: 'displace', meaning: 'v. 取代，迫使离开' },
    { word: 'disposal', meaning: 'n. 处理，处置' },
    { word: 'disseminate', meaning: 'v. 传播，散布' },
    { word: 'distinction', meaning: 'n. 区别，荣誉' },
    { word: 'distort', meaning: 'v. 扭曲，歪曲' },
    { word: 'distract', meaning: 'v. 分散注意力' },
    { word: 'diverse', meaning: 'adj. 多样的' },
    { word: 'diversification', meaning: 'n. 多样化' },
    { word: 'diversity', meaning: 'n. 多样性' },
    { word: 'doctrine', meaning: 'n. 教义，学说' },
    { word: 'domestic', meaning: 'adj. 国内的，家庭的' },
    { word: 'dominant', meaning: 'adj. 主导的' },
    { word: 'dominate', meaning: 'v. 支配，主宰' },
    { word: 'donation', meaning: 'n. 捐赠' },
    { word: 'dramatic', meaning: 'adj. 戏剧性的' },
    { word: 'drought', meaning: 'n. 干旱' },
    { word: 'duration', meaning: 'n. 持续期间' },
    { word: 'dynamic', meaning: 'adj. 动态的，有活力的' },
    { word: 'ecological', meaning: 'adj. 生态的，生态学的' },
    { word: 'ecosystem', meaning: 'n. 生态系统' },
    { word: 'editorial', meaning: 'adj. 编辑的 n. 社论' },
    { word: 'efficiency', meaning: 'n. 效率' },
    { word: 'elaborate', meaning: 'adj. 精心制作的 v. 详述' },
    { word: 'elevate', meaning: 'v. 提升，提高' },
    { word: 'eligible', meaning: 'adj. 合格的' },
    { word: 'eliminate', meaning: 'v. 消除，淘汰' },
    { word: 'elite', meaning: 'n. 精英' },
    { word: 'embrace', meaning: 'v. 拥抱，包含' },
    { word: 'emerge', meaning: 'v. 出现，浮现' },
    { word: 'emission', meaning: 'n. 排放，散发' },
    { word: 'empathy', meaning: 'n. 共情，同理心' },
    { word: 'empirical', meaning: 'adj. 以经验为依据的' },
    { word: 'employment', meaning: 'n. 就业，雇用' },
    { word: 'empower', meaning: 'v. 授权，赋予力量' },
    { word: 'encounter', meaning: 'v./n. 遭遇，邂逅' },
    { word: 'endeavor', meaning: 'v./n. 努力，尝试' },
    { word: 'endorse', meaning: 'v. 赞同，背书' },
    { word: 'enforce', meaning: 'v. 执行，强制' },
    { word: 'engage', meaning: 'v. 参与，吸引' },
    { word: 'enhance', meaning: 'v. 提升，增强' },
    { word: 'enormous', meaning: 'adj. 巨大的' },
    { word: 'enrich', meaning: 'v. 丰富，充实' },
    { word: 'enroll', meaning: 'v. 注册，登记' },
    { word: 'enterprise', meaning: 'n. 企业，事业' },
    { word: 'enthusiasm', meaning: 'n. 热情' },
    { word: 'entrepreneurial', meaning: 'adj. 企业家的，创业的' },
    { word: 'environmental', meaning: 'adj. 环境的' },
    { word: 'epidemic', meaning: 'n. 流行病' },
    { word: 'equate', meaning: 'v. 等同，相等' },
    { word: 'equitable', meaning: 'adj. 公平的，公正的' },
    { word: 'equivalent', meaning: 'adj. 等价的 n. 等价物' },
    { word: 'erosion', meaning: 'n. 侵蚀，腐蚀' },
    { word: 'essential', meaning: 'adj. 基本的，本质的' },
    { word: 'establish', meaning: 'v. 建立，确立' },
    { word: 'estate', meaning: 'n. 房地产，庄园' },
    { word: 'ethical', meaning: 'adj. 伦理的，道德的' },
    { word: 'ethnic', meaning: 'adj. 民族的，种族的' },
    { word: 'evaluate', meaning: 'v. 评估，评价' },
    { word: 'evaporate', meaning: 'v. 蒸发，消失' },
    { word: 'evidence', meaning: 'n. 证据，迹象' },
    { word: 'evolution', meaning: 'n. 进化，演变' },
    { word: 'exacerbate', meaning: 'v. 加剧，恶化' },
    { word: 'exaggerate', meaning: 'v. 夸张' },
    { word: 'examine', meaning: 'v. 检查，考试' },
    { word: 'exceed', meaning: 'v. 超过' },
    { word: 'exception', meaning: 'n. 例外' },
    { word: 'excess', meaning: 'n. 过度' },
    { word: 'exclude', meaning: 'v. 排除，排斥' },
    { word: 'execute', meaning: 'v. 执行' },
    { word: 'exemplify', meaning: 'v. 例示' },
    { word: 'exert', meaning: 'v. 施加' },
    { word: 'exhaust', meaning: 'v. 耗尽' },
    { word: 'exhibit', meaning: 'v. 展览 n. 展品' },
    { word: 'expand', meaning: 'v. 扩大，膨胀' },
    { word: 'expedition', meaning: 'n. 探险' },
    { word: 'expenditure', meaning: 'n. 支出' },
    { word: 'expertise', meaning: 'n. 专长' },
    { word: 'exploit', meaning: 'v. 利用，剥削' },
    { word: 'explore', meaning: 'v. 探索' },
    { word: 'exposure', meaning: 'n. 暴露，接触' },
    { word: 'extend', meaning: 'v. 延伸' },
    { word: 'extensive', meaning: 'adj. 广泛的' },
    { word: 'external', meaning: 'adj. 外部的' },
    { word: 'extract', meaning: 'v. 提取 n. 摘录' },
    { word: 'extraordinary', meaning: 'adj. 非凡的' },
    { word: 'extreme', meaning: 'adj. 极端的' },
    { word: 'facilitate', meaning: 'v. 促进，使便利' },
    { word: 'facility', meaning: 'n. 设施，设备' },
    { word: 'factor', meaning: 'n. 因素，要素' },
    { word: 'feasible', meaning: 'adj. 可行的' },
    { word: 'fluctuation', meaning: 'n. 波动，起伏' },
    { word: 'formidable', meaning: 'adj. 强大的，令人敬畏的' },
    { word: 'foster', meaning: 'v. 促进，培养' },
    { word: 'holistic', meaning: 'adj. 整体的，全面的' },
    { word: 'hypothesis', meaning: 'n. 假说' },
    { word: 'inevitable', meaning: 'adj. 不可避免的' },
    { word: 'infrastructure', meaning: 'n. 基础设施' },
    { word: 'integrity', meaning: 'n. 诚实正直，完整性' },
    { word: 'intervention', meaning: 'n. 干预，介入' },
    { word: 'lucrative', meaning: 'adj. 获利丰厚的' },
    { word: 'meticulous', meaning: 'adj. 一丝不苟的' },
    { word: 'mitigate', meaning: 'v. 缓解，减轻' },
    { word: 'notion', meaning: 'n. 观念，看法' },
    { word: 'paramount', meaning: 'adj. 最重要的' },
    { word: 'perseverance', meaning: 'n. 毅力，坚持' },
    { word: 'prevalent', meaning: 'adj. 普遍存在的' },
    { word: 'prosperity', meaning: 'n. 繁荣，昌盛' },
    { word: 'recreational', meaning: 'adj. 娱乐的，消遣的' },
    { word: 'resilience', meaning: 'n. 韧性，恢复力' },
    { word: 'sustainable', meaning: 'adj. 可持续的' },
  ]
};
