/**
 * Layer 2: Decoration Mood Pool
 *
 * Characters have their own daily lives — training, patrol, cooking, reading, etc. —
 * independent of user interaction. This module now reads AI-generated daily events
 * that were previously written to the ambient memory layer (category='decoration_mood').
 *
 * The hardcoded MOOD_POOLS have been removed. Events are now generated by AI
 * via generateDailyEvents() in ai.ts, each with valence/arousal coordinates
 * that affect the character's ongoing mood through the PANAS emotion event system.
 */

import { useAppStore } from '../store';

export interface MoodPoolEntry {
  word: string;        // event description, e.g. "练完球"
  feelingWord: string; // maps to emotion dictionary, e.g. "舒畅"
  kind: string;        // frontend sticker type
}

/**
 * Get today's decoration mood entries for a character.
 * Reads from ambient memory (category='decoration_mood') for today's date.
 * Returns the most recent entry (or null if none).
 */
export function getTodaysDecorationMood(characterId: string): MoodPoolEntry | null {
  const state = useAppStore.getState();
  const bank = state.characterMemoryBank[characterId] || [];
  const today = new Date().toISOString().split('T')[0];

  const todayMoods = bank
    .filter(m => m.category === 'decoration_mood' && m.summary?.includes(today))
    .sort((a, b) => b.createdAt - a.createdAt);

  if (!todayMoods.length) return null;

  const latest = todayMoods[0];
  return {
    word: latest.tags?.[1] || latest.summary.slice(0, 20),
    feelingWord: latest.tags?.[2] || latest.tags?.[0] || '平静',
    kind: 'sparkle',
  };
}

/**
 * Get ALL today's decoration mood entries (for MoodManager UI).
 */
export function getCharacterMoodPool(characterId: string): MoodPoolEntry[] {
  const state = useAppStore.getState();
  const bank = state.characterMemoryBank[characterId] || [];
  const today = new Date().toISOString().split('T')[0];

  return bank
    .filter(m => m.category === 'decoration_mood' && m.summary?.includes(today))
    .sort((a, b) => b.createdAt - a.createdAt)
    .map(m => ({
      word: m.tags?.[1] || m.summary.slice(0, 20),
      feelingWord: m.tags?.[2] || m.tags?.[0] || '平静',
      kind: 'sparkle' as const,
    }));
}

/**
 * Check if today's decoration moods have already been written for this character.
 */
export function hasTodaysDecorationMoods(characterId: string): boolean {
  const state = useAppStore.getState();
  const bank = state.characterMemoryBank[characterId] || [];
  const today = new Date().toISOString().split('T')[0];
  return bank.some(m => m.category === 'decoration_mood' && m.summary?.includes(today));
}

/**
 * Write one decoration mood entry to a character's ambient memory layer.
 * Called by generateDailyEvents() for each AI-generated event.
 */
export function writeDecorationMoodToMemory(
  characterId: string,
  word: string,
  feelingWord: string,
  valence: number,
  arousal: number,
): void {
  const state = useAppStore.getState();
  const today = new Date().toISOString().split('T')[0];

  const moodEntry = `今天${word}（${feelingWord}）`;
  state.addCharacterMemory(characterId, {
    type: 'observation',
    content: moodEntry,
    summary: `[${today}] ${moodEntry}`,
    tags: ['装饰心情', word, feelingWord],
    valence,
    arousal,
    importance: 1,
    layer: 'ambient',
    category: 'decoration_mood',
  });

  // Also post an emotion event so PANAS mood reflects it
  state.addEmotionEvent({
    characterId,
    paDelta: valence > 0.6 ? 0.4 : valence > 0.4 ? 0.1 : valence < 0.3 ? -0.2 : 0,
    naDelta: valence < 0.3 ? 0.4 : valence < 0.4 ? 0.15 : 0,
    word: feelingWord,
    valence: (valence - 0.5) * 2, // convert 0~1 to -1~+1
    arousal,
    matchSource: 'free_form',
    source: 'decoration',
  });
}
